version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: neurotech-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - neurotech_db_data:/var/lib/mysql

volumes:
  neurotech_db_data: