spring:
  application:
    name: challenge-java-developer
  datasource:
      url: ${DB_URL:jdbc:mysql://localhost:3306/neurotech}
      username: ${DB_USER:credito}
      password: ${DB_PASS:credito1234}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 5000
  error:
    include-stacktrace: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    org.springframework.web: DEBUG










